export const LOGGED_IN = 'auth/LOGGED_IN';
export const LOGGED_OUT = 'auth/LOGGED_OUT';
export const LOGIN_FAILED = 'LOGIN_FAILED'


export const START_ORDER = 'START_ORDER'
export const FINISHED_ORDER = 'FINISHED_ORDER'
export const FAILED_ORDER = 'FAILED_ORDER'


export const FETCHED_REQUESTS = 'FETCHED_REQUESTS'
export const FETCHING_REQUESTS = 'FETCHING_REQUESTS'
export const FETCH_REQUESTS_FAILED = 'FETCH_REQUESTS_FAILED'


export const FETCHING_USERS = 'FETCHING_USERS'
export const FETCHED_USERS = 'FETCHED_USERS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'

export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const LOADED_PRODUCTS = 'LOADED_PRODUCTS'
export const LOAD_PRODUCTS_FAILED = 'LOAD_PRODUCTS_FAILED'

export const LOADING_CATEGORY = 'LOADING_CATEGORY'
export const LOADED_CATEGORY = 'LOADED_CATEGORY'
export const LOAD_CATEGORY_FAILED = 'LOAD_CATEGORY_FAILED'

export const LOADING_SUPPLIER = 'LOADING_SUPPLIER'
export const LOADED_SUPPLIER = 'LOADED_SUPPLIER'
export const LOAD_SUPPLIER_FAILED = 'LOAD_SUPPLIER_FAILED'

export const FETCHING_PRICE = 'FETCHING_PRICE'
export const FETCHED_PRICE = 'FETCHED_PRICE'
export const FETCH_PRICE_ERROR = 'FETCH_PRICE_ERROR'

export const CART_UPDATE = 'CART_UPDATE'
export const CART_ADD = 'CART_ADD'
export const CART_DELETE = 'CART_DELETE'
export const CART_UPDATE_FAILED = 'CART_UPDATE_FAILED'

export const ERROR = 'ERROR'
